### ISSUE TITLE
Feature request: Have you considered a different pubsubclient library

### ISSUE THREAD

**Issue by KmanOz** [arendst/Sonoff-MQTT-OTA-Arduino#11]
Hi

Great work. I can see a lot of thought has gone into this. Have you considered using lmroy/pubsubclient? I ask because it expands on the original work that Nick O'Leary did and adds a whole bunch of classes, in particular the ability to send QOS 1 & 2 messages, keepalive settings in the sketch etc etc, Would really round off your work quite nicely.

Otherwise great job.

**Comment by arendst** [comment]
I've tried AsyncMqtt and had the code working but only with workarounds to the then available version.

I'll look into your suggested pubsubclient in the near future.

**Comment by eazuka** [comment]
I think @KmanOz is spot on, please look into it. great work

**Comment by ionciubotaru** [comment]
https://github.com/Imroy/pubsubclient - it's a good library, you can perform OTA over MQTT and send QOS 1 messages.

**Comment by TotallyInformation** [comment]
It would also be really helpful if the telemetry output used a Last Will & Testement with a timeout related to the telemetry period.

In that way, if the Sonoff device hasn't responded after the telemetry period has passed, the telemetry message could switch to "Offline" (if using messageformat 1) or something similar otherwise.

I use this extensively with other devices and it is great for being able to alert when devices go offline.

**Comment by arendst** [comment]
LWT message updated to optional JSON format. To sync LWT message with telemetry messages you'll have to change define MQTT_KEEPALIVE in PubSubClient to the same value as TELEPERIOD.
