### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by Beetle-II** [arendst/Sonoff-MQTT-OTA-Arduino#50]
Hello.
I'm trying upgrade from version 1.0.32 to version 2.0.5.
Through the web-server I get the message:

```
Upload failed
Update error code 2
Update error code 8
```

Through OTA I get the message:
`Failed HTTP error: connection refused`

**Comment by Beetle-II** [comment]
I compared the information from the two modules and found the difference:
Flash size 1024kB
Sketch flash size is **4096K**

It seems I had forgotten to change the size of the left and 4096K.

It is possible to flash without connecting FTDI?

**Comment by arendst** [comment]
Nope. You''ll need ftdi.

**Comment by Beetle-II** [comment]
Hello.
I installed 2 Sonoff relay.
I want to when you two short presses the button instead of switching the relay send mqtt command to switching of the second relay.

Do not figured out where in the code to insert the following command.
If possible please help me ...

**Comment by arendst** [comment]
For version 2.0.6 look in sonoff.ino around line 1185

**Comment by patbeirne** [comment]
Beetle,
You can also try using the "buttontopic" feature.

For example, if you have two sonoffs called: "kitchen" and "hallway", you can set the buttontopic on the hallway sonoff so that it sends out the string "kitchen". Then you can use the hallway sonoff button to control the **_other_** sonoff.

See also: [https://github.com/arendst/Sonoff-MQTT-OTA-Arduino/wiki/Control-a-Sonoff-using-a-remote-button]

Pat
